name: Python Script Workflow

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2.3.4 # Checkout the repository content to github runner.

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 # Install the python version needed

      - name: Install Python dependencies
        run: python -m pip install --upgrade pip certifi chardet idna requests selenium urllib3 ipapi func_timeout random-word==1.0.7 pyyaml webdriver-manager packaging pyvirtualdisplay # Install the dependencies (if needed)

      - name: Execute Python script # Run the script.py file to get the latest data
        run: python MicrosoftRewardsBot.py
